name: uquiz_parser
description: A sample uquiz parser
version: 1.0.0

environment:
  sdk: '^3.4.0'

dependencies:
  dio: ^5.4.3+1
  html: ^0.15.4
  pocketbase: ^0.18.1
  xml: ^6.5.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
