name: uquiz_parser
description: A sample uquiz parser
version: 1.0.0

environment:
  sdk: '^3.4.0'

dependencies:
  dio: ^5.4.3+1
  pocketbase: ^0.18.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
